const DIFFICULTY_BEGINNER_ROUTE = '/play/beginner';
const DIFFICULTY_ROOKIE_ROUTE = '/play/rookie';
const DIFFICULTY_INTERMEDIATE_ROUTE = '/play/intermediate';
const DIFFICULTY_COMMAND_ROUTE = '/play/command';
const DIFFICULTY_GOD_ROUTE = '/play/god';

export {
    DIFFICULTY_INTERMEDIATE_ROUTE,
    DIFFICULTY_GOD_ROUTE,
    DIFFICULTY_COMMAND_ROUTE,
    DIFFICULTY_ROOKIE_ROUTE,
    DIFFICULTY_BEGINNER_ROUTE
};